set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

bind-key -r f run-shell "tmux neww ~/bin/tmux-sessionizer"

bind-key -r J run-shell "~/bin/tmux-sessionizer ~/projects/provisioning"
bind-key -r F run-shell "~/bin/tmux-sessionizer ~/projects/actual-server"
bind-key -r K run-shell "~/bin/tmux-sessionizer ~/projects/IAC"
bind-key -r D run-shell "~/bin/tmux-sessionizer ~/projects/dotfiles"
